### ISSUE TITLE
[Frontend] Parse receipt pdf to get name for profile

### ISSUE THREAD

**Issue by daniel-weisdorf** [daniel-weisdorf/justice-league#7]
discuss - either the frontend parses name before sending to backend, or backend parses name and sends to frontend for profile

**Comment by ahmedadan** [comment]
I'd prefer the parsing happen on the frontend, less data in transit overall but either way works.

**Comment by daniel-weisdorf** [comment]
big agree on not shipping the receipt pdf - only issue is that the backend has to trust the frontend fully when creating a record, a malicious user could hit the create record endpoint directly without actually having uploaded a pdf

that being said, you can also just make a fake pdf, so im open to trusting the frontend in this mvp

**Comment by daniel-weisdorf** [comment]
this aint happening gonna close this
